%% read library information file.
function [ libInfo ] = readLibInfo( libInfoFile )
% Author: Ylonge.
% Date: 2017/10/14.
% Function: Read file generated by LibVC encoder based on HM-16-15.
%   --libInfo: struct storing library information.
%   --libInfoFile: file containing library information.
fidLibInfoFile = fopen( libInfoFile );
if(fidLibInfoFile == -1)
    fprintf(2, ferror(fidLibInfoFile));
    return;
end

listSymbol = {
    'LIBVCNumOfRefLibPic';
    'candidatePicPocList';
    'NewLibPicPocList';
    'OrgLibPicPocList'; 
    'LibPicFreqList'; % 5
    'LibDeltaQPList';
    'CenterCostList';
    'ClusterCostList';
    'LibGeneratorType'; 
    'AdaptiveQPMethod'; % 10
    'intraPicPocList';
    'refLibPicList';
    'HistDiffOfIPic';
    'area'; % 15
};
numSymbol = length(listSymbol);

libInfo = {};

while(~feof(fidLibInfoFile))
    strLineExtract = fgetl(fidLibInfoFile);
    if(isempty(strLineExtract))
        continue;
    end
    
    for idxSymbol = 1: numSymbol - 1
        symbol = listSymbol{idxSymbol};

        if(size(strfind(strLineExtract, symbol)))
            startPos = strfind(strLineExtract, symbol) + size(symbol, 2);
            dataSymbol = str2num(strLineExtract(startPos: end));
            libInfo = [libInfo; dataSymbol];
        end
    end
    if(size(strfind(strLineExtract, symbol)))
        strLineExtract = fgetl(fidLibInfoFile);
        dataSymbol = str2num(strLineExtract(:));
        libInfo = [libInfo; dataSymbol];
    end
end
fclose(fidLibInfoFile);
end